# Gram-Schmidt process



## 1.  Instructions Gram-Schmidt process
In this assignment you will write a function to perform the Gram-Schmidt procedure, which takes a list of vectors and forms an orthonormal basis from this set.
As a corollary, the procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit.

### Matrices in Python
Remember the structure for matrices in *numpy* is,
```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
You can access the value of each element individually using,
```python
A[n, m]
```
You can also access a whole row at a time using,
```python
A[n]
```

You can select whole columns at a time.
This can be done with,
```python
A[:, m]
```
which will select the m'th column (starting at zero).

In this exercise, you will need to take the dot product between vectors. This can be done using the @ operator.
To dot product vectors u and v, use the code,
```python
u @ v
```

All the code you should complete will be at the same level of indentation as the instruction comment.


In [6]:
import numpy as np
import numpy.linalg as la

In [7]:
verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001


def gsBasis(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]):
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i) :
            # Complete the code to subtract the overlap with previous vectors.
            # you'll need the current vector B[:, i] and a previous vector B[:, j]
            e_j = B[:, j]
            proj = (np.dot(B[:, i],e_j)*e_j)
            B[:, i] = B[:, i] - proj    ## EDIT THIS
        # Next insert code to do the normalisation test for B[:, i]
        if la.norm(B[:, i]) > verySmallNumber:
            B[:, i] = B[:, i]/la.norm(B[:, i]) ## EDIT THIS
        else :
            B[:, i] = np.zeros_like(B[:, i])      
            
    # Finally, we return the result:
    return B

# This function uses the Gram-schmidt process to calculate the dimension
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero,
# the sum of all the norms will be the dimension.
def dimensions(A) :
    return np.sum(la.norm(gsBasis(A), axis=0))


In [8]:
## Using numpy implementation, 

def gs(X):
    Q, R = np.linalg.qr(X) # mode='complete')
    return Q

### Testing 

In [9]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)


M = np.array([[1,1,1],[1,1,0], [1,0,0]], dtype=np.float_)

In [10]:
gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [11]:
gs(V)

array([[-0.40824829,  0.1814885 ,  0.04982278, -0.89325973],
       [-0.        , -0.1088931 ,  0.99349591,  0.03328918],
       [-0.81649658, -0.50816781, -0.06462163,  0.26631346],
       [-0.40824829,  0.83484711,  0.07942048,  0.36063281]])

In [12]:
## So we have a big problem here, the python implemntation differs from 
## our implementation. Bonus point if you can figure out why.
# There is a sign difference but I don't know why, I thin they are using different implementation
#np.testing.assert_almost_equal(gs(V), gsBasis(V))

In [13]:
# See what happens for non-square matrices
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [14]:
gs(A)

array([[-0.23643312, -0.18771349, -0.22132104],
       [-0.15762208, -0.74769023,  0.64395812],
       [-0.15762208, -0.57790444, -0.72904263],
       [-0.94573249,  0.26786082,  0.06951101]])

In [15]:
dimensions(A)

3.0

In [16]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [17]:
dimensions(B)

3.0

In [18]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [19]:
dimensions(C)

2.0

## 2. Page Rank Algorithm

### Question

Describe the PageRank Algorithm as seen in the python notebook on Page_rank.ipynb and relate it with the use of eigne-values and eigen-vectors. 

Provide your answers here. 

### Description

PageRank is an analysis algorithm that assigns a numerical weighting to each element of a set of web pages, with the purpose of "measuring" its relative importance within the set. PageRank works by counting the number and quality of links to a web page to determine a rough estimate of how important the web page is. The underlying assumption is that more important websites are likely to receive more links from other websites.

The rank of the page is a result of an iterative process based on the webgraph, created by all World Wide Web pages as nodes and hyperlinks as edges. A hyperlink to a page counts as a vote of support. The PageRank of a page is depends on the number and PageRank metric of all pages that link to it i.e "incoming links". A page that is linked to by many pages with high PageRank receives a high rank itself.

### The algorithm
- The algorithm starts by creating a sparse square "web graph" $M$ matrix where position $(i.j)$ is set to value $1$ if there is a link between page $i$ and page $j$. If one page is a sink i.e it it has no outgoing links it will be assumed that it links out to all other pages in the collection. Their PageRank scores are therefore divided evenly among all other pages. In other words, to be fair with pages that are not sinks, these random transitions are added to all nodes in the Web.


- Each column $j$ in the matrix represent the number of outgoing links from page j. To make sure all links has the same weight all columns are then normalized.


- The PageRank theory holds that an imaginary surfer who is randomly clicking on links will eventually stop clicking. The probability, at any step, that the person will continue is a damping factor $d$. Various studies have tested different damping factors, but it is generally assumed that the damping factor will be set around 0.85.


- The vector $v$ is randomly initialized and is updated iteratively using the following algorithm until convergence. 

$\hat{M} = d * M + \frac{(1-d)}{number of pages} * Ones$
 
repeat until convergence:

$v_{new} = \hat{M} * v_{old}$

where $M$ is the web graph matrix with it's columns normalized.

- The PageRank values $v$ after convergence are the entries of the eigenvector of the modified matrix $\hat{M} $rescaled so that each column adds up to one. i.e $v$ can be seen as the eigen values matrix for the transformation matrix $\hat{M}$ with eigen value 1.